# PyTorch / TF

In [6]:
import numpy as real_np

x = real_np.arange(10)
condlist = [x<3, x>5]
choicelist = [x, x**2]
selected = real_np.select(condlist, choicelist)
real_np.multiply.outer(selected, x)

array([[  0,   0,   0,   0,   0,   0,   0,   0,   0,   0],
       [  0,   1,   2,   3,   4,   5,   6,   7,   8,   9],
       [  0,   2,   4,   6,   8,  10,  12,  14,  16,  18],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0],
       [  0,  36,  72, 108, 144, 180, 216, 252, 288, 324],
       [  0,  49,  98, 147, 196, 245, 294, 343, 392, 441],
       [  0,  64, 128, 192, 256, 320, 384, 448, 512, 576],
       [  0,  81, 162, 243, 324, 405, 486, 567, 648, 729]])

In [3]:
import numpy

In [5]:
def fn():
    x = numpy.empty((10,10))

    for i in range(10):
        for j in range(10):
            selected = i if i < 3 else (i ** 2 if i > 5 else 0)
            x[i, j] = selected * j
    return x
fn()

array([[  0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.],
       [  0.,   1.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.],
       [  0.,   2.,   4.,   6.,   8.,  10.,  12.,  14.,  16.,  18.],
       [  0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.],
       [  0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.],
       [  0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.],
       [  0.,  36.,  72., 108., 144., 180., 216., 252., 288., 324.],
       [  0.,  49.,  98., 147., 196., 245., 294., 343., 392., 441.],
       [  0.,  64., 128., 192., 256., 320., 384., 448., 512., 576.],
       [  0.,  81., 162., 243., 324., 405., 486., 567., 648., 729.]])

In [ ]:
!pip install torch torchvision

In [7]:
import torch

x = torch.arange(10)
selected = torch.where(x < 3, x, torch.where(x > 5, x ** 2, torch.zeros_like(x)))
torch.tensordot(selected, x, dims=0)

tensor([[  0,   0,   0,   0,   0,   0,   0,   0,   0,   0],
        [  0,   1,   2,   3,   4,   5,   6,   7,   8,   9],
        [  0,   2,   4,   6,   8,  10,  12,  14,  16,  18],
        [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0],
        [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0],
        [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0],
        [  0,  36,  72, 108, 144, 180, 216, 252, 288, 324],
        [  0,  49,  98, 147, 196, 245, 294, 343, 392, 441],
        [  0,  64, 128, 192, 256, 320, 384, 448, 512, 576],
        [  0,  81, 162, 243, 324, 405, 486, 567, 648, 729]])

In [ ]:
!pip install tensorflow==2.0.0-alpha0 

In [8]:
import tensorflow as tf

@tf.function
def tf_fn():
    x = tf.range(10)
    selected = tf.where(x < 3, x, tf.where(x > 5, x ** 2, tf.zeros_like(x)))
    return tf.tensordot(selected, x, axes=0)

tf_fn()

<tf.Tensor: id=29, shape=(10, 10), dtype=int32, numpy=
array([[  0,   0,   0,   0,   0,   0,   0,   0,   0,   0],
       [  0,   1,   2,   3,   4,   5,   6,   7,   8,   9],
       [  0,   2,   4,   6,   8,  10,  12,  14,  16,  18],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0],
       [  0,  36,  72, 108, 144, 180, 216, 252, 288, 324],
       [  0,  49,  98, 147, 196, 245, 294, 343, 392, 441],
       [  0,  64, 128, 192, 256, 320, 384, 448, 512, 576],
       [  0,  81, 162, 243, 324, 405, 486, 567, 648, 729]], dtype=int32)>